CREATE TABLE dept 
( DEPTNO   NUMBER(3) PRIMARY KEY, 
  DNAME    VARCHAR2(16), 
  LOC    VARCHAR2(16)); 
 
CREATE TABLE emp  
( EMPNO  NUMBER(4) PRIMARY KEY, 
  ENAME  VARCHAR2(16), 
  JOB  VARCHAR2(16), 
  MGR  NUMBER(4), 
  HIREDATE  DATE, 
  SAL  NUMBER(7, 2), 
  COMM  NUMBER(7, 2), 
  DEPTNO  NUMBER(3) NOT NULL REFERENCES DEPT(DEPTNO)); 
  
BEGIN
  INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
  INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES (20, 'RESEARCH', 'DALLAS');
  INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES (30, 'SALES', 'CHICAGO');
  INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES (40, 'OPERATIONS', 'WASHINGTON (D.C.)');
  INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES (50, 'MARKETING', 'BOSTON');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('error');
END;
/

BEGIN
  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('17-NOV-81', 'DD-MON-RR'), 5000, NULL, 10);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-MAY-81', 'DD-MON-RR'), 2850, NULL, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-JUN-81', 'DD-MON-RR'), 2450, NULL, 10);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-APR-81', 'DD-MON-RR'), 2975, NULL, 20);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-SEP-81', 'DD-MON-RR'), 1250, 1400, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEB-81', 'DD-MON-RR'), 1600, 300, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('08-SEP-81', 'DD-MON-RR'), 1500, NULL, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7900, 'JAMES', 'CLERK', 7698, TO_DATE('03-DEC-81', 'DD-MON-RR'), 950, NULL, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-FEB-81', 'DD-MON-RR'), 1250, 500, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7902, 'FORD', 'ANALYST', 7566, TO_DATE('03-DEC-81', 'DD-MON-RR'), 3000, NULL, 20);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-DEC-81', 'DD-MON-RR'), 800, NULL, 20);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('09-DEC-82', 'DD-MON-RR'), 4000, NULL, 20);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7876, 'ADAMS', 'CLERK', 7788, TO_DATE('12-JAN-83', 'DD-MON-RR'), 1100, NULL, 20);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7934, 'MILLER', 'CLERK', 7782, TO_DATE('22-JAN-82', 'DD-MON-RR'), 1300, NULL, 10);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-MAY-81', 'DD-MON-RR'), 2850, NULL, 30);

  INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
  VALUES (7935, 'JONES', 'ACCOUNT', 7782, TO_DATE('22-JAN-82', 'DD-MON-RR'), 1700, NULL, 10);
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('error');
    ROLLBACK;
END;
/

