INSERT INTO dept (DEPTNO, DNAME, LOC)
VALUES (10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO dept (DEPTNO, DNAME, LOC)
VALUES (20, 'RESEARCH', 'DALLAS');

INSERT INTO dept (DEPTNO, DNAME, LOC)
VALUES (30, 'SALES', 'CHICAGO');

INSERT INTO dept (DEPTNO, DNAME, LOC)
VALUES (40, 'OPERATIONS', 'DALLAS');

INSERT INTO dept (DEPTNO, DNAME, LOC)
VALUES (50, 'MARKETING', 'BOSTON');

COMMIT;
