/* Generated By:JavaCC: Do not edit this line. NihonglishConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NihonglishConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int I = 5;
  /** RegularExpression Id. */
  int YOU = 6;
  /** RegularExpression Id. */
  int HOME = 7;
  /** RegularExpression Id. */
  int STORE = 8;
  /** RegularExpression Id. */
  int GOING = 9;
  /** RegularExpression Id. */
  int AS_FOR = 10;
  /** RegularExpression Id. */
  int TO = 11;
  /** RegularExpression Id. */
  int PERIOD = 12;
  /** RegularExpression Id. */
  int QUESTION_MARK = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<I>",
    "<YOU>",
    "<HOME>",
    "<STORE>",
    "<GOING>",
    "\"as for\"",
    "\"to\"",
    "\".\"",
    "\"?\"",
  };

}
